apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: demo-rollout-bg
  namespace: lab
spec:
  replicas: 4
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: demo-rollout-bg
  template:
    metadata:
      labels:
        app: demo-rollout-bg
    spec:
      containers:
      - name: app
        image: argoproj/rollouts-demo:blue
        ports:
        - containerPort: 8080
  strategy:
    blueGreen:
      activeService: rollout-active
      previewService: rollout-preview
      autoPromotionEnabled: false
