apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: demo-rollout
  namespace: lab
spec:
  replicas: 4
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: demo-rollout
  template:
    metadata:
      labels:
        app: demo-rollout
    spec:
      containers:
      - name: app
        image: argoproj/rollouts-demo:blue
        ports:
        - containerPort: 8080
  strategy:
    canary:
      analysis:
        templates:
        - templateName: success-rate
        startingStep: 1
        args:
        - name: service-name
          value: demo-rollout-svc
      steps:
      - setWeight: 25
      - pause:
          duration: 5s
      - setWeight: 50
      # Manual promotion step (indefinite pause)
      - pause: {}
      - setWeight: 100
