apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-generator
  namespace: lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-generator
  template:
    metadata:
      labels:
        app: log-generator
    spec:
      containers:
      - name: generator
        image: chentex/random-logger:latest
        args: ["100", "400"] # min/max delay in ms
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            memory: 64Mi
