apiVersion: batch/v1
kind: CronJob
metadata:
  name: redis-backup
  namespace: lab
spec:
  schedule: "0 2 * * *" # Every day at 2:00 AM
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup
            image: redis:7.0-alpine
            command:
            - /bin/sh
            - -c
            - "redis-cli -h redis-headless.lab.svc.cluster.local -p 6379 SAVE && echo 'Backup triggered'"
            resources:
              requests:
                cpu: 50m
                memory: 64Mi
              limits:
                cpu: 100m
                memory: 128Mi
          restartPolicy: OnFailure
