apiVersion: apps/v1
kind: Deployment
metadata:
  name: hpa-demo
  namespace: lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hpa-demo
  template:
    metadata:
      labels:
        app: hpa-demo
    spec:
      containers:
      - name: php-apache
        image: registry.k8s.io/hpa-example@sha256:581697a37f0e136db86d6b30392f0db40ce99c8248a7044c770012f4e8491544
        ports:
        - containerPort: 80
        # БАГ: нет resources.requests.cpu. HPA по CPU-утилизации не сможет
        # посчитать процент -> targets покажут <unknown>/50% и масштабирования
        # не будет.
