apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-port
  namespace: lab
spec:
  ingressClassName: nginx
  rules:
  - host: port.lab.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend: { service: { name: web-a, port: { number: 8080 } } }
